#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later

build() {
    local mod

    add_module "dm-crypt"
    add_module "dm-integrity"
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules "/crypto/"
    fi

    add_module "cdrom"
    add_module "loop"
    add_module "dm-snapshot"
    add_module "overlay"

    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    add_binary "/usr/lib/libgcc_s.so.1"
    add_binary /usr/lib/udev/cdrom_id
    add_binary blockdev
    add_binary cryptsetup
    add_binary dmsetup
    add_binary losetup
    add_binary mountpoint
    add_binary truncate
    add_binary gpg
    add_binary grep

    if command -v pv >/dev/null 2>&1; then
        add_binary pv
    else
        warning 'pv not found; falling back to cp for copy to RAM'
    fi

    add_file /usr/lib/udev/rules.d/60-cdrom_id.rules
    add_file /usr/lib/udev/rules.d/10-dm.rules
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file /usr/lib/udev/rules.d/95-dm-notify.rules
    add_file /usr/lib/initcpio/udev/11-dm-initramfs.rules /usr/lib/udev/rules.d/11-dm-initramfs.rules
    if [[ $ARCHISO_GNUPG_FD ]]; then
        mkdir -m 0700 -- "$BUILDROOT/gpg"
        gpg --homedir "$BUILDROOT/gpg" --import <&"$ARCHISO_GNUPG_FD"

    fi
    add_runscript
}

help() {
    cat <<HELPEOF
  This hook loads the necessary modules for boot.
HELPEOF
}
